// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQzIYXFH6DmhMjZJsxnt75mIttLsm8ZLc',
    appId: '1:224269108898:web:690cf7f43d1464c828b9fb',
    messagingSenderId: '224269108898',
    projectId: 'neurocare-123ab',
    authDomain: 'neurocare-123ab.firebaseapp.com',
    storageBucket: 'neurocare-123ab.appspot.com',
    measurementId: 'G-PC7MNVCZ2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdfVIwmMz4tosKcxFS0XGikMAEm5UOGV4',
    appId: '1:224269108898:android:a3e256cf1790fbc728b9fb',
    messagingSenderId: '224269108898',
    projectId: 'neurocare-123ab',
    storageBucket: 'neurocare-123ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT-ng9uKZvZ3WeMJYyAUXzXq5vmDnxYVw',
    appId: '1:224269108898:ios:3958e663a811027028b9fb',
    messagingSenderId: '224269108898',
    projectId: 'neurocare-123ab',
    storageBucket: 'neurocare-123ab.appspot.com',
    iosBundleId: 'com.example.neurooooo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT-ng9uKZvZ3WeMJYyAUXzXq5vmDnxYVw',
    appId: '1:224269108898:ios:26fbf3653317220d28b9fb',
    messagingSenderId: '224269108898',
    projectId: 'neurocare-123ab',
    storageBucket: 'neurocare-123ab.appspot.com',
    iosBundleId: 'com.example.neurooooo.RunnerTests',
  );
}
